import { Header } from "@/components/layout/Header"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"

function StaticLayout({ title, onNav, children }: { title:string; onNav:any; children: React.ReactNode }) {
  return <div className="min-h-screen bg-white"><Header onNav={onNav} /><div className="mx-auto max-w-3xl px-4 py-12"><h1 className="text-3xl font-bold mb-6">{title}</h1><Card><CardContent className="p-8 prose prose-zinc max-w-none text-sm leading-relaxed">{children}</CardContent></Card></div></div>
}
export const SecurityPage = ({onNav}:{onNav:any}) => <StaticLayout title="Security" onNav={onNav}><p><strong>Cloudflare-first:</strong> R2 encryption at rest AES-256, TLS in transit.</p><ul className="list-disc pl-5"><li>Tokens: crypto.randomBytes(32) + nanoid, 256-bit entropy, never sequential IDs</li><li>Passwords: bcryptjs 12 rounds, never stored plaintext</li><li>JWT httpOnly secure cookies, SameSite Lax</li><li>Turnstile anti-bot on upload/auth</li><li>Rate limiting: 20 uploads/hr, 100 downloads/hr per IP via D1</li><li>Files streamed, not buffered. Worker never holds >5MB in memory.</li><li>Cron cleanup deletes expired R2 objects + D1 rows</li></ul></StaticLayout>
export const FeaturesPage = ({onNav}:{onNav:any}) => <StaticLayout title="Features" onNav={onNav}><ul className="list-disc pl-5 space-y-2"><li>Drag & drop, multi-file, 50 files per transfer, 2GB per file</li><li>Chunked 5MB resumable uploads with auto-retry</li><li>Secure shareable links /d/:token</li><li>Expiry 1-30 days, download limits, password protection</li><li>Email share, message, zip-all download</li><li>Dashboard, download analytics, history</li><li>Guest uploads with owner token</li><li>API with key auth</li></ul></StaticLayout>
export const HowItWorksPage = ({onNav}:{onNav:any}) => <StaticLayout title="How it works" onNav={onNav}><ol className="list-decimal pl-5 space-y-2"><li>Upload → chunked to R2 bucket filedrop-transfers/{'{transferId}'}/{'{filename}'}</li><li>Transfer row created in D1 with secure token</li><li>Generate /d/:token link</li><li>Share anywhere</li><li>Recipient opens /d/:token → D1 lookup → Turnstile optional → password check</li><li>Stream from R2 via Worker (no credential exposure)</li><li>Log download_events</li><li>Cron checks expiry / maxDownloads → delete R2 objects → delete D1 rows</li></ol></StaticLayout>
export const PrivacyPage = ({onNav}:{onNav:any}) => <StaticLayout title="Privacy" onNav={onNav}><p>We store files temporarily only. No permanent assets. Files auto-deleted after expiry. We do not scan content. Metadata retained for abuse prevention 30 days. EU GDPR compliant deletion via Cron.</p></StaticLayout>
export const TermsPage = ({onNav}:{onNav:any}) => <StaticLayout title="Terms" onNav={onNav}><p>Do not upload illegal content. Abuse leads to IP ban via D1 security_events. Service provided as-is on Cloudflare edge. Rate limits enforced.</p></StaticLayout>
